### PR TITLE
require fluentd module explicitly

### PR DESCRIPTION
**Pull request by repeatedly**
For v0.14

### CODE REVIEW

**Comment by repeatedly** [comment]
@y-ken Could you merge this patch and release new version?

**Comment by y-ken** [comment]
Hi

I'm afraid this repository head has updated with v0.5.0 which has supported fluentd v0.12.
For now, how should I fix for the issue?
Is It just adding `require 'fluent/config/error'` for head of `anonymizer.rb`?

**Comment by repeatedly** [comment]
Yes.

**Comment by y-ken** [comment]
@repeatedly 
I have added the code snippet and released with v0.5.1. Could you check it as you expected?
https://github.com/y-ken/fluent-plugin-anonymizer/commit/4d38cbe8a625c8ecb5a9238fd786c43b6a116c60

**Comment by y-ken** [comment]
If these problem has fixed, please close the pr?

**Pull request closed without merging**
