### PR TITLE
Add filter plugin

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
See #6

**Comment by y-ken** [comment]
Great! Thank you!

**Comment by okkez** [comment]
@y-ken Could you merge this PR?
Do you have any concern?

**Comment by repeatedly** [comment]
@y-ken ping?

**Comment by y-ken** [comment]
Now I have checked the code. Sorry I kept you waiting so long.

**Comment by y-ken** [comment]
Hi @okkez @repeatedly 
Now I have checked the code.
Sorry I kept you waiting so long.

**Comment by okkez** [comment]
Thanks!!

**Comment by y-ken** [comment]
Released v0.4.0 today!
https://rubygems.org/gems/fluent-plugin-anonymizer

**Pull request merged**
