### PR TITLE
Migrate to v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
I've migrated this plugin to use v0.14 API.
**Notice:** This PR contains BRAKING CHANGES.

Even if this PR is acceptable, please don't merge immediately.

First, we should release dependency Fluentd version locked version to ensure lock dependency for Fluentd v0.12.
And then, please merge this PR.
Finally, we should bump up dependent Fluentd version to 0.14.4 or later, bump up major version, and publish to rubygems.

And Fluentd upstream developer says that "don't manipulation tag in output plugin, use labels. If a plugin can implement same feature in output and filter plugin, we recommend to use filter and abandon output plugin." See: https://github.com/y-ken/fluent-plugin-anonymizer/pull/18#issuecomment-244884172

### CODE REVIEW

**Comment by cosmo0920** [comment]
BTW: Fluentd v0.14 does not support tag manipulation.
See this tweet (twitter): https://twitter.com/tagomoris/status/773068341804011520

We shall drop support `out_anonymizer` for this supporting v0.14 PR.

@y-ken What do you think of that? Is this v0.14 upstream decision acceptable?

**Comment by cosmo0920** [comment]
> We shall drop support out_anonymizer for this supporting v0.14 PR.
> Because out and filter versions of anonymizer provide same functionality except for routing.

I decided to preserve and migrate output version of anonymizer plugin.
But I dropped tag manipulation operation support.
`Fluent::XXX::Mixin` style is not recommended way since v0.14.
So, we should avoid to use mixing style of tag handling feature in Fluentd plugins.

How about current revision of v0.14 migration?

**Comment by y-ken** [comment]
Hi @cosmo0920 
I'm sorry for late response.
Instead of mixin, we can use `extract_placeholders` to rewrite tag. I think it can be keep output plugin version isn't you?
http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12#output-plugins-using-mixins

But we do not recommend to use output plugin, we recommend filter plugin.
Thus, we accept to drop support output plugin in this pull-request.

**Comment by cosmo0920** [comment]
Thank you for your comment.

> But we do not recommend to use output plugin, we recommend filter plugin.
> Thus, we accept to drop support output plugin in this pull-request.

I think that dropping output anonymizer plugin is too early for users.
Instead, displaying deprecated warnings when using output anonymizer plugin is better.

**Comment by y-ken** [comment]
Sure. Let's keep output plugin. I have switched the readme order stating filter first.
https://github.com/y-ken/fluent-plugin-anonymizer/commit/12df69be94fb68b4905a05dafe95853a06db22ed

**Comment by cosmo0920** [comment]
Any news?
Or, we should take over this project in @fluent-plugins-nursery?

**Comment by y-ken** [comment]
I'm very sorry for replying.
I've merged and checking the result of latest TravisCI test.
After success, I'll release it soon.

**Comment by cosmo0920** [comment]
Thanks!

**Comment by y-ken** [comment]
I have released fluent-plugin-anonymizer v1.0.0 now
https://rubygems.org/gems/fluent-plugin-anonymizer

**Comment by y-ken** [comment]
Thank you for everything!!

**Pull request merged**
