### PR TITLE
Use travis container

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by y-ken** [comment]
Hi @okkez  Thank you.
It is good to support container to improve performance and testing with ruby 2.3.

I want to keep backward compatibility with fluentd v0.10.x like this.
https://github.com/yunomu/fluent-plugin-cloudwatch/blob/master/.travis.yml

**Comment by okkez** [comment]
OK.
Do you need Ruby 1.9.3 support?

**Comment by y-ken** [comment]
Yes. I need to support both.

* td-agent1 (fluentd v0.10.x with ruby 1.9.3) 
* td-agent2 (fluentd v0.12.x with ruby 2.x).

#### in `.travis.yml`

```
gemfile:
  - gemfiles/fluentd_0.10.gemfile
  - gemfiles/fluentd_0.12.gemfile
```

#### in `gemfiles/fluentd_0.12.gemfile`

```
source "https://rubygems.org"

gem "fluentd", "~> 0.12.0"

gemspec :path => "../"
```

**Comment by okkez** [comment]
OK. I will revive Ruby 1.9.3 support.

**Comment by okkez** [comment]
I use https://github.com/thoughtbot/appraisal to manage gemfiles.

**Comment by y-ken** [comment]
Looks nice!
Could you remove `gemfiles/*.gemfile.lock` files if it doesn't need?

**Comment by okkez** [comment]
> Could you remove gemfiles/*.gemfile.lock files if it doesn't need?

We need `gemfiles/*.gemfile.lock` when we want to lock gem versions.
If we don't need to lock gem versions, we can remove them.

I will remove them.

**Comment by y-ken** [comment]
Great!

**Pull request merged**
